### PR TITLE
You thought I would not do it right

### PR DESCRIPTION
**Pull request by iDroid27210**
sToP wItH mEntIoNs EvEryWhERe

### CODE REVIEW

**Comment by ArtutoGamer** [comment]
you can do it on kick and softban please? xd

**Comment by iDroid27210** [comment]
I DON'T KNOW HOW TO ADD COMMITS TO A PR

**Comment by ArtutoGamer** [comment]
Commit to your own branch

**Comment by ArtutoGamer** [comment]
Not hackban ;-;

**Comment by iDroid27210** [comment]
yes im dumb xd

**Comment by iDroid27210** [comment]
EL DUMBASS escribió: "done"

**Comment by ArtutoGamer** [comment]
where xd

**Comment by ArtutoGamer** [comment]
and softban bans > clears 1 day > unban

**Comment by ArtutoGamer** [comment]
GRaCIas

**Comment by DismissedGuy** [comment]
Such conversation XD

**Pull request merged**
